<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    
     public function buscarProducto($id)
    {
         
         return  $this->getEntityManager()
                ->createQuery('SELECT * FROM AppBundle:Product p WHERE p.id = :id ')
                 ->setParameter('id', $id)
                 ->getSingleScalarResult();
         
         
    }
         
      
    }
