producto_index:
    path:     /
    defaults: { _controller: "AppBundle:Producto:index" }
    methods:  GET

producto_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Producto:show" }
    methods:  GET

producto_new:
    path:     /new
    defaults: { _controller: "AppBundle:Producto:new" }
    methods:  [GET, POST]

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Producto:edit" }
    methods:  [GET, POST]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Producto:delete" }
    methods:  DELETE
    
producto_buscarProducto:
    path:     /buscarProducto
    defaults: { _controller: "AppBundle:Producto:buscarProducto" }
    methods:  [GET, POST]
